// --- SWAPPED TO AUTOGENERATED DATA ---
// The original data is below, commented out for easy rollback.
// To restore, uncomment the original export and comment out the autogenerated one.

export * from './permissionsData.generated';

/*
// ORIGINAL DATA:
// import { parsePermissionsData } from '../utils/permissionsParser';
// import { SupportedActions } from '../types/permissions';
// ... (rest of the original file remains here, commented out) ...
*/
