// AUTOGENERATED FROM Permission Set - IA.xlsx (UPDATED)
// Review before replacing permissionsData.ts

import { Domain } from '../types/permissions';

export const permissionsData: Domain[] = require('./permissions_xlsx.json')
  .filter((row: any) => row.Domain && row.Permission)
  .reduce((domains: Domain[], row: any) => {
    let domain = domains.find(d => d.name === row.Domain);
    if (!domain) {
      domain = { name: row.Domain, subdomain: row['Sub-domain'] || '-', permissions: [] };
      domains.push(domain);
    }
    domain.permissions.push({
      name: row.Permission,
      isScopable: row['Scopable?'] === 'Scopable today',
      supportedActions: row['Supported actions'],
      isSensitive: row['Sensitive data flag'] === 'Yes',
      subdomain: row['Sub-domain'] || '-',
      noScopeLimit: row['Scopable?'] === 'Not applicable',
    });
    return domains;
  }, []); 